### ISSUE TITLE
SEO対策 検索に引っかかりやすくする

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-app#153]
seiryofes.comを本格的に2023年度星陵祭Webサイトとして運用していくにあたって、中学生や一般客が「星陵祭」って検索したときに出てこないのはよくない

6月中でお願いします🙇‍♂️

**Comment by ekkekuru2** [comment]
@TK-7728 
ここの文章をもっとちゃんとしたい
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/834e8f5d-b16a-4091-bf06-cfc20dd968b2)

それからLINEやSNSで共有するときにプレビューされる画像と文章が変なのでその辺(おそらくOGPという規格?)を調査して欲しい
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/893d566f-a27c-419a-b9cc-35a9e9d1391f)

**Comment by hibiyahibiyahibiya** [comment]
質問なんですが、
この画像の一番下のdescriptionはそれとは関係ありませんか？
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/327ee2a6-7aec-42a3-b763-f3b05e72196d)

**Comment by ekkekuru2** [comment]
あ、そうかも、
#182をマージしよう

**Comment by hibiyahibiyahibiya** [comment]
#220 が解決したのに伴いclose
