### ISSUE TITLE
（メモ）公演名の長さと空席状況について

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#175]
公演名が長すぎると、空席状況のマークが下に降りてしまう。

![Screenshot 2023-07-03 at 23-45-12 星陵祭](https://github.com/hibiya-itchief/quaint-app/assets/128669695/d4cd726a-527b-4abc-8e08-fc6a4181f7f5)
この図を見ると、全角13文字はセーフ、14文字はアウトとなる
（ただし、この先デザインが大きく変わるようなことがあれば、境界線も変わる）
そんな知識のない利用者でも、これが正しい動作でないことは簡単に推察できてしまうので
長くならないよう入力フォームのときに弾けるようにしておきたい
e.g.「短く書いて」と注意書き＆全角13文字を超過したら警告をする　など
既に似た機構があったらこのissueは静かに消しておきます…

あと、2023/07/04時点の臨時的なDBを私がいじっているため、
seiryofes.comに行くと誰でも開発中なのを見ることができて
はずかしいです

**Comment by ekkekuru2** [comment]
んー文字数に関しては表示する環境で変わってくる(パソコンだと14文字でも問題なく表示出来てる。逆にもっと小さいスマホだと13文字以下でも崩れるかも)からAPI側で制限するのはやりたくないかも
フロントエンド側で、信号機の位置は絶対固定して、あふれる文字は折り返す、みたいにできないかな

**Comment by ekkekuru2** [comment]
ごめん開発用DB・API作るのさぼっちゃった。やっぱあった方がいいね。すぐ作ります

**Comment by ekkekuru2** [comment]
このリポジトリをPrivateにすればissueとかは非公開にできるんだけど、Privateにすると今使ってるGitHub Actionsとかの一部機能が有料になっちゃうから出来てないって感じです

**Comment by ItsukiKigoshi** [comment]
- https://github.com/hibiya-itchief/quaint-app/pull/247
で解決
