### ISSUE TITLE
（メモ）記法の統一について

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#176]
プログラムの書き方について。
おおまかに、
hoge_hoge（スネークケースとも）
hoge-hoge（ケバブケースとも）
hogeHoge（キャメルケースとも）
の３種類の書き方+αがある。

未熟であるがゆえに私は適当に気分で使い分けているのですが、
そこを統一した方がよいのだろうか…？

また、自分の担当した/group/index.vueにて
boolean型（論理型、trueかfalseという値をとる)
であることを示すために
searchBという変数を用意してしまい
我ながら癖が強く、
かえって可読性を下げてしまっているのではないかと心配している…

issueやbranchの題名もそうだが、
書き方を統一した方が組織としてよいのだろうか…？

一周回って、個性があふれていてよいのかもしれない……

**Comment by hibiyahibiyahibiya** [comment]
あまり関係ないことだが、
この変数がこういうことを表していて、この部分はこういう動作をさせるための部分だよーといったような指南（解読？）のコメントをどうやって記すか考えている。
例えばvueファイルでいえば、
//なんたら

/* なんたら */
（違いについては検索してほしい）
などといったコメントアウトのやり方があるが、
それを各内容にやっていては
逆にコメントが多すぎて見づらくなってしまう。
なので別ファイル(.md)に書いて、それを片手に各々解読して理解していくという形がよいのだろうか…

**Comment by ekkekuru2** [comment]
一応、javascript的にはたしか、hogeHogeのようなlowerCamelCaseを採用しているからそれに則って統一すべきなんだけど
APIと通信をするじゃないですか。quaint-apiはPythonで書かれてて、Pythonはhoge_hogeのsnake_caseを採用してるので、APIから返ってくるプロパティはsnake_caseにしてるんですね(taken_ticketsとか)。だからフロントエンド側でそれを格納する変数もsnake_caseにしてるって感じです。
今後はAPIが関与する変数はsnake_caseで関与しない変数はlowerCamelCaseでって感じでいきたい。ごちゃまぜで統一できてないのは確かにちょっと気持ち悪いけど
kebab-caseはなぜいるんだ！と思ったけど、HTMLとかCSSがkebab-caseなのでその辺に関わる名前はkebab-caseになってるのかも

**Comment by ekkekuru2** [comment]
指南・解読のコメント、別ファイルに分けるのができるならぜひやって欲しいかも

**Comment by hibiyahibiyahibiya** [comment]
別ファイルに分ける場合、たとえばindex.vueの解読ファイルの場合、
それをindex.vueと同じ場所に置くのと、
generalに同じフォルダー構成を用意して、そこにindex.vueの代わりに置くのと、どちらがよいでしょうか
前者の場合publicなので外部に見られる可能性があり、index.vueだけだと解読困難だったのが容易に理解できてしまう…と思ったのですが、それは別に問題ではないんですかね？
後者の場合ちょっと面倒かもしれません←

また、解読内容だけ書くか、あるいは
index.vueにコメントアウトを付けたver.として用意するか…
後者はindex.vueの内容を変えるたびに解読書も更新しないといけないので、
自分は手間の面で前者の方がよい気がします

**Comment by ekkekuru2** [comment]
index.vueと同じ場所に置くで良いと思う。たぶん読める人が見たら解読書なんかなくても一瞬で読める。セキュアな情報は公開リポジトリに載せてないから大丈夫だと思っている。脆弱性があったらやばいけど

俺も解読内容だけ書く前者で良いと思うな。変更がめんどくさくなってindex.vueと解読書に不整合が出るのは一番良くない
