### ISSUE TITLE
（めも）お気に入りハートマーク機構の改善

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#193]
今の扱い方より
もうちょっとよくできるはず……

**Comment by ekkekuru2** [comment]
そういえば、初見の人にはあのハートマークがお気に入りを保存して後から見返す機能だということが分かりづらい気がした

**Comment by hibiyahibiyahibiya** [comment]
/groupsでお気に入りとタグ表示があるのでそこで察してくれることを期待しましたが
さすがに厳しいですかね…
snackbarで「お気に入りに登録しました！」が頭によぎりましたが、
snackbar使いすぎな気もしてきました…
通知多すぎてうんざりするのと同じ現象でストレスになったら困ります

それか、/groupsの方の「お気に入り」タグにハートマークをつけるとかどうでしょう？
あんまり想像できないんですが、もしあったらハートマークがお気に入りのマークであることはわかりやすいと思います！！

**Comment by hibiyahibiyahibiya** [comment]
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/9f5f1407-6371-4cf7-88f0-dc5daaefbe72)
mdi-book-heartでやるとこんな感じです
mdi-heartはちょっと大きすぎてとりあえず不採用にしました

**Comment by ekkekuru2** [comment]
/groups の一覧ページのお気に入りボタンにアイコン入れるのは良いアイデアだと思う！
mdiアイコン見つけたのもさすが👍


group個別ページにもこんな感じにキャプション付けるのはどうかな、、？

![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/01df34c0-2ade-43f3-ad78-cc2765e586f2)

**Comment by ekkekuru2** [comment]
それと今iPhoneで見てたら、お気に入りボタンがはみ出して隠れちゃってるからその改善が必要そう

![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/502ff47d-5f82-4e44-9b81-a3eddbcb3efc)

**Comment by hibiyahibiyahibiya** [comment]
スマホだと見えない問題はちょうど今日梶谷のスマホ見て発見しました
このあたり、新デザインがくるまで手を付けない方がいいのかなあと悩んでいます

また、あそこに文字付けようとすると、
左だとTwitter/Instagramのアイコンと被る、
上or下だと文字が小さすぎるかなーという理由でできればアイコンだけで理解させたいです

ひとつは、これでいいねとは違う機能なのをほのめかす
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/cb77919d-40bc-46df-856f-92160bd47d9d)

もうひとつはハートマークを使わずブックマークであることを前面に押し出す
（お気に入りという名前からブックマークに変えるのもあり）
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/e4ce49e6-e98e-44eb-88c6-f6d85c6fbb7b)

いかがでしょう

**Comment by hibiyahibiyahibiya** [comment]
プラスの方、押したらマイナスにするようにしたらなんか微妙なので
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/7d2630b9-014f-4aa7-80e1-07781ea477cf)
mdi-heart-plus-outline→mdi-heartがよい気がします

**Comment by ekkekuru2** [comment]
ブックマークが好き

**Comment by ItsukiKigoshi** [comment]
やや議題とは異なるような気もしますが，もしブックマーク機能が頻繁に使用される機能なのであれば，以下のようにbottom navigationに入れても良いかと思いました（もし演劇以外の発表もこのサイトに掲載されるなら，すぐにお気に入りにアクセスできたら便利かも？）．
![image](https://github.com/hibiya-itchief/quaint-app/assets/67095865/72e9ed79-c040-4bff-b9d9-dd2f7b38cdb6)

**Comment by hibiyahibiyahibiya** [comment]
/groups内で完結するのであればピン留めアイコンとかもおもしろいかもしれませんね
ブックマーク一覧のページを/groupsとは別に作るのであればブックマークの方がいいと思いますが
