### ISSUE TITLE
整理券取得の際のエラーメッセージについて

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#197]
いま、

- すでにその整理券を所持している
- 同じ時間帯の整理券を所持している
- すでに満席である

の３つのエラーがすべて「予期せぬエラー」というsnackbarで表示されます
利用者目線、特に満席とそれ以外の区別がつかないため、エラーの原因がわからずに質問…という流れになってしまいます
なのでエラーメッセージを細分したい所存です。

また、すでに満席であることが明らか（赤信号時）な場合、dialog出さずにエラーsnackbarにしたい。
これは配布時間外の処理と同様に後でやっておきます。

**Comment by ItsukiKigoshi** [comment]
追記
### 予期せぬエラー
- 入校処理していない人が整理券を取得しようとした時

**Comment by hibiyahibiyahibiya** [comment]
* #244 
と合併
