### ISSUE TITLE
editページの公演削除について

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#200]
現在、バツボタンを押すと、すぐ成功snackbarが出て、公演が削除されます
しかし、そんな簡単に削除できるのは、例えば手が滑って押してしまったりした場合など、ちょっと危険な気がします
なのでできればdialogでも何でもいいんですけど、一回警告を挟んでおきたいと思います

とりあえず自分で検討しておきます

**Comment by hibiyahibiyahibiya** [comment]
うーん…
基本ownerに作らせて、二重チェックの要領でadminが確認・調整する…とかですかね？
代表者には間違えないようによーく確認させて（≒警告）
もしおかしいところをこちらで見つければこちらで直すあるいはその代表者に聞くなどするイメージです

その場合、公演の登録など早めにしてもらいたいですよね
あと、直前になって勝手に変更することのないよう、直前期は変更できなくするなどもした方がよいのかな…と考えています

**Comment by ekkekuru2** [comment]
- #209
