### ISSUE TITLE
アカウントのOwner表示

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#212]
https://github.com/hibiya-itchief/quaint-app/blob/969e45e5b8bee95a92d8757c9022f92cc076205f/layouts/default.vue#L32-L43

の部分、
現在は👑Adminの表示以外コメントアウトに入れて出ることのないようにしているが
そろそろOwnerをつけるので、ちゃんとOwnerになれていることを確認できるようにしたい

**Comment by ekkekuru2** [comment]
これ思ってた！頼む！

**Comment by ekkekuru2** [comment]
ownerていうのはシステム上の表記で利用者にはわかりづらいかもだから、「団体代表者」とかの方がいいかも

**Comment by ekkekuru2** [comment]
- #216
