### ISSUE TITLE
mainのtitle・titleTemplate関連が更新されていない

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#220]
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/715b3423-45a4-4a62-9e31-27bc24c5c956)
ただし、サイト内に入ってからはちゃんと変更が更新されている

**Comment by hibiyahibiyahibiya** [comment]
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/4ed024ed-8561-4845-9bd9-21283701d4d5)
更新されました

ただ、わがままなんですが、
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/51e589c0-8757-4352-a21a-4b6025de32bc)
あるいは
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/d3b123b5-8958-4c7e-b55a-56cf75090942)
の方が見栄えがいいんじゃないかなーと思いました(なんなら2023も不要かも)
前者はもちろん、後者も[このサイト](https://polidog.jp/2018/06/16/nuxt-head/#titletemplate%E3%81%8C%E9%82%AA%E9%AD%94%E3%81%AB%E3%81%AA%E3%82%8B%E5%A0%B4%E5%90%88%E3%81%AE%E5%AF%BE%E5%87%A6%E6%B3%95)の通りtitleTemplate上書きで簡単に作れます

**Comment by ekkekuru2** [comment]
なるほど、リンク先みたいにテンプレート上書きできるなら後者すごく良いね
それに変更しよう。してもらってもいい？

**Comment by ekkekuru2** [comment]
あとあれだね、検索結果の本文が

> Admin 団体代表者 校内入場処理済み 生徒用アカウント ...ってなってるのが気に食わないね

**Comment by hibiyahibiyahibiya** [comment]
そこってどこで直せるんですかね…
この前のTKのテコ入れで治るのかと思っていたんですが…

**Comment by ekkekuru2** [comment]
分からん()
metaタグのdescriptionあたりな気はするけど...
調べてみて欲しい....

**Comment by hibiyahibiyahibiya** [comment]
更新されていることを確認しました
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/ce7dd773-46ba-41ea-be56-825a36e23e96)
