### ISSUE TITLE
/groups 一覧ページをスマホで見た時の表示件数を多くする

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-app#226]
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/fe4c191d-4fd0-4902-af28-e3c642d0021b)

パソコンやタブレットで見る分には、サムネや説明文、タグ等情報が充実していて良いが、スマホで見ると、一画面に1・2団体くらいしか表示できず見づらい

スマホで開いたときだけこんな感じにする？

![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/011e8a7d-3a8f-4ec4-ae8a-a4f863b83ecc)

左:現行 右:スマホで見たとき 図が雑でごめん

いったんアサインは @ItsukiKigoshi 先輩にしてますが、 @hibiyahibiyahibiya の意見も聞きたい。
このissueは、この通りに実装するタスク、というよりはどうしたら良いかという議論のところからやりたいです。

**Comment by hibiyahibiyahibiya** [comment]
めちゃいいですね

ただ、横表示(現行表示じゃない方)に切り替える基準が考えものですね
スマホの縦横比はもちろん切り替えますけど、パソコンをフルスクリーンからどんどん縦長にしていったとき、どのタイミングで横表示に切り替えるのかということです

あと、団体の画像をどう切るかも大事な気がします
現行表示だと団体の画像は上下から切りますが横表示だと左右から切ることになりますよね
例として21Rの画像は上下から切っていった場合きれいに21Rという文字が入っていますが、
これを両横から切っていった場合下のように21Rという文字が途切れてしまうと思います
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/5914489c-915e-49ad-b428-897edccdba43)
そのあたり横表示を導入するなら団体代表者に伝えておくべきなのかなと思います

**Comment by ItsukiKigoshi** [comment]
@hibiyahibiyahibiya さんの発言にも関連して質問です．各団体が登録するサムネイル画像の縦横比はしていされていますか？もし @ekkekuru2 がこのIssueの冒頭で示してくれているデザインにするなら，サムネイル画像は縦長（例えば縦向きのA4）の方がありがたいです．

**Comment by ekkekuru2** [comment]
間違えた

**Comment by ekkekuru2** [comment]
> ただ、横表示(現行表示じゃない方)に切り替える基準が考えものですね
スマホの縦横比はもちろん切り替えますけど、パソコンをフルスクリーンからどんどん縦長にしていったとき、どのタイミングで横表示に切り替えるのかということです

これは確かウェブ開発のデファクトスタンダードみたいな基準があった気がする。「レスポンシブデザイン」とかでググると横幅が何px以下になったらスマホ用みたいなのが見つかる

**Comment by ItsukiKigoshi** [comment]
@ekkekuru2 
実装してみました．えいすけのイメージとcorrespondしていますか？
<img width="378" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/fdeb39ea-67a3-4e7d-8bdb-1ffaf2014269">

**Comment by ekkekuru2** [comment]
すごく良いです！ありがとうございます
サムネイルの縦横比は正方形が良さそうですかね？
あと現状、group.description が入ってないように見えるんですが、スペース的に入れられそうですか？

**Comment by ItsukiKigoshi** [comment]
とりあえず納得できる仕上げまでして[当IssueのBranch](https://github.com/hibiya-itchief/quaint-app/tree/226-groups-%E4%B8%80%E8%A6%A7%E3%83%9A%E3%83%BC%E3%82%B8%E3%82%92%E3%82%B9%E3%83%9E%E3%83%9B%E3%81%A7%E8%A6%8B%E3%81%9F%E6%99%82%E3%81%AE%E8%A1%A8%E7%A4%BA%E4%BB%B6%E6%95%B0%E3%82%92%E5%A4%9A%E3%81%8F%E3%81%99%E3%82%8B) にCommitしておきました．
> サムネイルの縦横比は正方形が良さそうですかね？
コードの書きやすさを優先してv-avatarで実装したため正方形になっています．クラスによってポスターのアスペクト比がまちまちな現状を踏まえると，正方形は現実的な選択肢かと思います．
>あと現状、group.description が入ってないように見えるんですが、スペース的に入れられそうですか？
わざと入れていないです．group.descriptionを入れるとv-cardsのheightが一意に定まらないのが嫌で入れませんでした．group.descriptionが無い方がデザイン的にはすっきりすると思うのですが，UX的にあった方がよければ入れる方法を検討します．もし無くて良いのなら無くしたい．

**Comment by ItsukiKigoshi** [comment]
gourp.descriptionを追加した上で#230 #237 を吸い上げるとこんなデザイン？
<img width="375" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/6709778a-6232-4db9-af13-aaf9a9427b72">

**Comment by ekkekuru2** [comment]
branchへのpushありがとうございます！

> コードの書きやすさを優先してv-avatarで実装したため正方形になっています．クラスによってポスターのアスペクト比がまちまちな現状を踏まえると，正方形は現実的な選択肢かと思います．

なるほど、ちなみに今は縦と横のどちらを切り落として正方形にしていますか？
それと、正方形で行くのであれば、現行の(パソコンやタブレットで見たときの)/groups一覧表示や、group個別ページ(/groups/_groupId)のv-cardにも正方形でサムネイルを表示するように統一することになるのかなと思うのですが、その際にバランスがどうなのかちょっとイメージがついていないです。

個人的には4:3とかでどちらのパターンでも上手く行ったりしないかなーと勝手に想像してます

**Comment by ekkekuru2** [comment]
### group.description
- 個人的には入れた方が良いかなと思いました。
- 星陵祭パンフレット(紙)には、団体名・演目名・イメージ画像・説明文がおそらく載ると思うので、それと同等の情報がwebサイトでも得られた方が良いと思いました。
- v-cardのheightが決まらない問題は、一定の文字数で切って、残りは...みたいにして対応出来ないですかね、、？
- あと、v-cardのheightに関連して、タグが増えた時に、どういう挙動になるんだろうと思いました
- 確かにデザイン的に文字が多いとごちゃごちゃして見づらいですよねーー、、、descriptionの文字をちょっと薄く・細く・小さくする、もしくは、演目名・団体名を濃く・太くするみたいな、フォントや色のアプローチでうまく工夫できたら良いのですが

**Comment by ItsukiKigoshi** [comment]
> 星陵祭パンフレット(紙)には、団体名・演目名・イメージ画像・説明文がおそらく載ると思うので、それと同等の情報がwebサイトでも得られた方が良いと思いました。

- 確かに，説明文が無いと，観客が見ず知らずのクラスの演劇をクリックするきっかけが減る．
- 参考にYouTubeを見てみると，PC版ではDescriptionがあってMobile版には無いのよね．これまで気づかなかったけど，流石YouTubeは実装が細かい．MUIを使ってる点でも参考になりそう．このYouTube Mobile版のUIにDescription足した感じで私たちのも作れたら良いんだけど．
![image](https://github.com/hibiya-itchief/quaint-app/assets/67095865/6abb26b5-5589-4351-8687-3793c72bc1bb)

![image](https://github.com/hibiya-itchief/quaint-app/assets/67095865/e01cfd3c-988e-48f6-9fdf-f64c7cb4ecc4)

> v-cardのheightが決まらない問題は、一定の文字数で切って、残りは...みたいにして対応出来ないですかね、、？

- 出来ます．

> あと、v-cardのheightに関連して、タグが増えた時に、どういう挙動になるんだろうと思いました

タグが折り返され（wrapされ）て2行になります．

> 確かにデザイン的に文字が多いとごちゃごちゃして見づらいですよねーー、、、descriptionの文字をちょっと薄く・細く・小さくする、もしくは、演目名・団体名を濃く・太くするみたいな、フォントや色のアプローチでうまく工夫できたら良いのですが

- この辺の軽微なデザインの調整なんだけど，しょっちゅうyarn runが落ちて毎回yarn devコマンドを打つのがめちゃくちゃストレス．出来なくはないが時間がめちゃかかるのよねえ...Storybookとか導入してGUIでデザインできたりしないだろうかとwonderingしてる．

**Comment by ekkekuru2** [comment]
mergeしない旨了解です

### 縦横比について
- v-imgの[aspect-ratio](https://v2.vuetifyjs.com/ja/components/images/#aspect-ratio)というpropsで縦横比を固定
- heightで高さを固定
- (クラ代にはなるべく4:3(とか指定した縦横比)の画像を用意してもらうが、)[contain](https://v2.vuetifyjs.com/ja/components/images/#contain)というpropsでどんな縦横比の画像が来ても切り取られて見えなくなることがないように
みたいなアプローチはどうでしょうか..!割と最適解なのかもと思ってます
### PC・タブレットとモバイルでの表示について
- 個人的には切り替えたいです(PC・タブレットでは現行の表示をする)。
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/b6e9f49d-ee2e-4fd2-a55c-6243d4e04efc)
同じくYouTubeのUIで大きな画面で一覧表示したときのものですが、こんな感じのイメージ？
- PC・タブレットとモバイルで表示を分けるというのは[breakpoint-service](https://zenn.dev/kenji7157/articles/b6841d9e90ca4a#2.-breakpoint-service)というのを使えばできそうです
- まあこれは本当に好みの問題ですよね。どうしよう
- 考える際に、作ってくださった横長のv-cardのデザインを大きい画面で表示した時のキャプチャをいただけるとイメージしやすいのかなと思いました。
### group.description
- class="grey--text text--caption"あたりを設定するといい感じに薄くできると思います。が、
- モバイル版YouTubeの表示をみて確かに、モバイルではdescriptionの表示なしの方が良いと思いました。



codespace無料インスタンスなので仕方ない部分はありそうですが、確かにちょっとデザインを変えるたびに毎回ビルド待つのはストレスですよね。Storybook知らなかったです。すごそう調べてみます

全体的に、なんか僕は全然コーディングしてないのに口ばっかでごめんなさい！！！

**Comment by ItsukiKigoshi** [comment]
@ekkekuru2 
サムネイル画像の縦横比「4:3」は，縦4:横3ですか？それとも縦3:横4？イメージしている縦横比があれば教えてほしいです！個人的には映画のポスターと同じA判（縦√2:横1）みたいに縦長が映えそうかと思うけど，色々な縦横比で実験してみないと分からない部分が多い．

**Comment by ekkekuru2** [comment]
僕は横4:縦3(一般的な写真の縦横比)のイメージでした
A版サイズも気になります

**Comment by ItsukiKigoshi** [comment]
@ekkekuru2 
現状，サムネイル画像の縦横比についてクラス代表にはどう伝わってるの？特に指定している？

**Comment by ekkekuru2** [comment]
夏休み前の参代で今年度のWebページについて告知した際には「サムネイル画像をアップロードしてください」という指示はしていなくて、「クラ代のみなさんはサムネイル画像をアップロードすることも出来ます」っていう案内レベルに留めてました(このissueみたいに変更をする可能性があったのと、まだそこまで準備できているクラスは多くないだろうという想定から)

これから縦横比が決まったら、縦横比を指定した上で、「アップロードしてください」という指示にするつもりでした

これからWebページ専用のサムネイル画像を作るクラスも増えると思うので、早めに指定してあげるべきですね、、、じゃないと作り直しになっちゃう

**Comment by ItsukiKigoshi** [comment]
了解．縦横比を指定するとしたらいつ？
あと，現状縦横比の選択肢はこんなもん（縦:横）？
- A判（√2:1）
- 写真（3:4）
- 動画（9:16）
- 正方形（1:1）

**Comment by ekkekuru2** [comment]
考えてなかったです。
このissueが解決すれば決まると思うので、先輩が無理せず実装出来そうななるべく早い段階、ですかね、、？
それとも、どちらかといえば実装よりも議論をいつまでに終わらせるかという意味合いで、期限切らせていただいた方が良い？

縦横比の候補はOKです！

**Comment by ItsukiKigoshi** [comment]
うん，期限切った方が良さそう！夏休みの終わりが近づくにつれて各クラスがどんどんサムネイルをアップロードしそう．

**Comment by ekkekuru2** [comment]
7月中だと早いですか？

**Comment by ItsukiKigoshi** [comment]
了解しました．7月中で出来るだけやってみましょう．

**Comment by ItsukiKigoshi** [comment]
## lg以上: 縦3横4が良さそう
<img width="1789" alt="Screenshot 2023-07-27 at 17 22 36" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/f2d27837-8855-4880-a711-39bf5a2d94b2">
## md: 縦3横4が良さそう
<img width="996" alt="Screenshot 2023-07-27 at 17 23 14" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/bb7c07c9-1e4e-444c-a2ae-9d1209795698">
<img width="1988" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/e580e966-17cf-483e-9d9d-e7bfb3efb8a1">

**Comment by ekkekuru2** [comment]
分かりやすくありがとうございます！！

md以上,smは4:3にしているとのことですが、感覚的にですが、4:3よりも横に細長く見えます...なんででしょう

### xsについて
- PC・タブレット用とスマホ用にサムネイル画像を2つアップロードするというのは現状できない。ので、

1. 各団体代表者には横4:縦3の縦横比を推奨


-  個人的にはこのぐらいのフォント・サイズと色のバランスならdescriptionを入れてもデザインが大きく崩れていないと思った→descriptionも入れたい
- 上のキャプチャ画像の4:3のものだと、画像の横幅が大きく、縦幅が小さいためdescriptionを入れるのは難しそう

2. descriptionを入れられるようにサムネ表示用に確保するv-imgのサイズは 
横：v-cardに対する割合で指定(30%くらい？)
縦：v-cardのheightをpxで絶対指定して統一、v-imgはv-cardに対して100%の高さ

- 画像が切り取られることは避けたい

3. containを適用


とかでどうでしょうか。うーんわかりづらくてすみません

**Comment by ekkekuru2** [comment]
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/ff0ae419-d9be-4f75-9e2e-b54251f13cea)

**Comment by ekkekuru2** [comment]
4:3の画像を推奨にしておいて、containで表示、ピッタリの縦横比にはならず上下に余白ができるのは諦める

**Comment by ekkekuru2** [comment]
でもそうなると、4:3にこだわる理由はあまり無いか

**Comment by hibiyahibiyahibiya** [comment]
ちょっと気になったのですが
xsにdescriptionを追加して、かつ画像を切り取らずに縮小すると、
小さい表示物でごちゃごちゃした、非常に情報量の多い画面になってしまうのではないでしょうか

スマホ画面の小さなもの、生徒は読めますが、親世代は老眼などで非常に読みにくいのではないでしょうか

**Comment by ItsukiKigoshi** [comment]
> md以上,smは4:3にしているとのことですが、感覚的にですが、4:3よりも横に細長く見えます...なんででしょう

- 画像がない場合に入っている単色は，アスペクト比に関係なく横に引き伸ばされます．

- xsについては，縦長に切り取るなどして以下の画像のようにするか，説明文を削るかですね．説明文を入れないとクリックしにくいかもしれないので入れられたら入れたいよねえ．
あと，api-devの方では，各クラスが出しているサムネイルとの相性を見られないので何とも言い難い．
![image](https://github.com/hibiya-itchief/quaint-app/assets/67095865/6a439112-9319-4fd6-8085-8d72292ab66c)

**Comment by ItsukiKigoshi** [comment]
@ekkekuru2 
特に問題がなければPRつくります！
優先順位次第だけど，次/groups/で実装されたら便利な機能は[これ](https://github.com/hibiya-itchief/quaint-app/issues/230)かな

**Comment by ekkekuru2** [comment]
画像の縦横比はこれで行きますか？containつけた方が良いかなと思うんですが

**Comment by ItsukiKigoshi** [comment]
ではcontainつけます！縦横比は，色々試して1番情報がすっきり収まったので今の状態になってます．https://github.com/hibiya-itchief/quaint-app/issues/230 とかやったらまたデザイン変わりそうだけど．
他に気になることはありますか？

**Comment by ekkekuru2** [comment]
ありがとうございます
他には特にありません
PRお願いします
