### ISSUE TITLE
/tickets 持ってる整理券一覧のデザイン改良

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-app#227]
結局整理券は目視で確認ということになった(チーフからは必要無いとのことだったが、余裕があれば来年以降のことを考えてQRコードで整理券の正当性を検証できる機能もつけたいと個人的には考えてます)

時間が無い中で、各クラスの受付担当者はたくさんの入場者を捌かないといけない。その際に、第何公演なのか、何人入場できるのか、チェックする必要があるが、現状その表示が見づらいと思った。
今年は特に、紙整理券とオンライン整理券が入り混じるのでパッと見でその整理券は合ってるのかわかる必要がありそう

**Comment by ekkekuru2** [comment]
案の一つは
- #194

**Comment by ItsukiKigoshi** [comment]
現在出来る工夫として，公演時間15分前-公演終了時間までに該当するチケットを「Up-Next（次はこちら）」 などとして一番上に大きく表示したい．まずはデザインを考えます．

**Comment by ekkekuru2** [comment]
あそれは生きてます！チーフ会からGIFを入れて欲しいと言われました

**Comment by ekkekuru2** [comment]
booking.comいいですね

**Comment by ItsukiKigoshi** [comment]
@hibiyahibiyahibiya or @ekkekuru2 さんへ，
「チーフ会からGIFを入れて欲しいと言われました」といった細かい仕様が書かれたチーフからの仕様書がどこかにありましたら，Discord @ItsukiKigoshi 宛てに送っていただきたいです．

**Comment by ItsukiKigoshi** [comment]
- [ ] ここの説明が分かりにくい．「あなたは入場前です」のように表示すれば良いかな．その下の説明文も，アイコンと箇条書き（1.,2.,3.,）を利用して簡潔に．また，「ユーザIDを表示する」はその場所である必要ある？必要ないなら良い場所を取りすぎな気がする
![image](https://github.com/hibiya-itchief/quaint-app/assets/67095865/10b4c00f-7844-46d1-824d-80ae8c93fc44)

**Comment by ekkekuru2** [comment]
覚えてないんですが、特に理由は無いと思います。
[v-expansion-panel](https://v2.vuetifyjs.com/ja/components/expansion-panels/#section-4f7f304465b9)の方が良さそう。たぶんv-expansion-panelを見つけられなかったからそれっぽい実装をしただけです。。。

**Comment by ekkekuru2** [comment]
commit流し読みですが見ました！現状すごく良さそうですありがとうございます
引き続きよろしくお願いします

**Comment by ItsukiKigoshi** [comment]
議論したの後PRにします．
- 公演20分前から公演終了までは「開場中」と表示
- 公演終了後はその旨を表示
- その他見やすさを改善

最新コミット↓
![](https://user-images.githubusercontent.com/67095865/256678844-4baef5da-756e-4b79-9918-b056c30cdb8c.png)

「会場中」の表示参考↓
![](https://user-images.githubusercontent.com/67095865/256661308-01de9249-d153-48de-aa68-6b4e1fe5206a.png)

**Comment by ItsukiKigoshi** [comment]
- [ ] 上演時間が終了した整理券に対するキャンセルを無効化 (using v-ifによる「キャンセル」ボタンの条件付きレンダリング)

**Comment by ItsukiKigoshi** [comment]
最新のスクリーンショットです（ユーザーIDのQRコードがたまにしか出てこない）

![image](https://github.com/hibiya-itchief/quaint-app/assets/67095865/313a7567-c59a-4d59-bad4-93575a85dc3a)
![image](https://github.com/hibiya-itchief/quaint-app/assets/67095865/39ffb17f-26c3-4f41-a908-53f6df25750d)
![image](https://github.com/hibiya-itchief/quaint-app/assets/67095865/76079448-1e74-4e3b-b092-fa12ead047fd)

**Comment by ekkekuru2** [comment]
今表示される順番ってどうなってますか、何かソートされてますか？

**Comment by ItsukiKigoshi** [comment]
公演時間順になっていると思います．これはえいすけが実装したわけじゃない？
` ticketInfos.sort((first, second) => {
        if (
          new Date(first.event.starts_at).getTime() <
          new Date(second.event.starts_at).getTime()
        )
          return -1
        else if (
          new Date(first.event.starts_at).getTime() >
          new Date(second.event.starts_at).getTime()
        )
          return 1
        else return 0
      })`

**Comment by ItsukiKigoshi** [comment]
最新のスクリーンショット．以前私が言っていた`公演時間20分前-公演終了時間までに該当する（開場中の）チケットを一番上に大きく表示`を実装．しかし，「開場中の整理券」と「取得済み整理券一覧」が上手く分かれていないので分かりにくいデザインになっている...どうすればいいんだろう．

↑通常時
↓開場中の整理券がある場合
<img width="373" alt="Screenshot 2023-07-29 at 13 41 22" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/5053dd74-d93d-43be-bdd2-42af0f9b19c3">
<img width="376" alt="Screenshot 2023-07-29 at 13 40 54" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/d1bec28b-eda4-49fe-b60d-ac6502cda964">

**Comment by ItsukiKigoshi** [comment]
@ekkekuru2 
ここまでで特に問題なければ，prつくります！

**Comment by ekkekuru2** [comment]
すごく良いアイデアだと思います、画像の縦横比はこれで行きますか？containつけた方がいいと思うんですが

**Comment by ItsukiKigoshi** [comment]
Containつけます！他に気になることはありますか？

**Comment by ekkekuru2** [comment]
ありがとうございます
他には特にありません
PRお願いします

**Comment by ItsukiKigoshi** [comment]
了解ですPRつくります！
縦横比難しいよね．YouTubeみたいに横長にすると他の情報が入らず，かと言って縦長にすると画像が小さくなる．
