### ISSUE TITLE
/groups/_groupId 【案】残席表示をアイコンにする

### ISSUE THREAD

**Issue by ItsukiKigoshi** [hibiya-itchief/quaint-app#231]
残席表示を色で表示すると，色盲の方や明るい場所で見えにくい可能性がある．アイコンを使用して「O（配布中）△（残りわずか）X（配布終了）-（配布前）」の4つを設けるのでどうだろう．「配布前」は分かりやすくグレーアウトする．

cf. TOHOシネマズ
<img width="821" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/a7db6dfb-c570-497e-8e9d-f36015571ad9">
<img width="980" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/d77671a9-86c8-48eb-9fea-f76ce72f4918">

**Comment by ItsukiKigoshi** [comment]
# 議論した後PRつくります
## 変更点
- ボタンの並び
- 配布状況の表示方法
- 再読込ボタンのre-design

最新コミット↓
<img width="562" alt="Screenshot 2023-07-28 at 8 17 49" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/a75fc8da-454b-4a1e-8d98-e9a0074da8fe">
<img width="1790" alt="Screenshot 2023-07-28 at 8 17 35" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/24dfa69a-4752-49bc-82ac-ea8bee654769">
<img width="562" alt="Screenshot 2023-07-28 at 8 17 49" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/280622e2-b537-415d-bb99-40c64f779b9b">

**Comment by ekkekuru2** [comment]
すごく良いと思います！
残りわずかや満席の時の表示も見たいです

**Comment by ItsukiKigoshi** [comment]
@ekkekuru2 
<img width="377" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/f042cf66-d3fb-4c0f-94eb-730b0eaaaf3b">
<img width="383" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/a23ca831-4c7c-4759-82cc-6416dfba09a1">

**Comment by ItsukiKigoshi** [comment]
もしかして，「配布時間外」の整理券を表示する必要は無い？予約する時に邪魔だよね

**Comment by hibiyahibiyahibiya** [comment]
たしかに予約するときにちょっと邪魔だとは思うのですが、配布の開始していない終了した公演の存在することは示したいです…
一瞬、(UI的観点はおいといて)配布時間外の公演一覧をexpansion panelでまとめて、最初は閉じた状態にしておけば両立できるのではと思いました

**Comment by ItsukiKigoshi** [comment]
> 配布の開始していない終了した公演の存在することは示したいです…

確かに,TOHOシネマズも終了した公演を表示している．いっそのこと公演名（e.g.「1日目第1公演」）を無くして，v-cardのheightを潰すか．
<img width="364" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/ae4d746a-7101-418c-aab8-231e8d7df87b">

**Comment by ItsukiKigoshi** [comment]
TOHOシネマズの実装を参考に表示数を多くしました．
<img width="374" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/a6735ed7-54ae-4b08-8d65-8cd85ba9e550">
<img width="1680" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/be24a95c-f9a6-4823-9c1b-da728f880656">

**Comment by ItsukiKigoshi** [comment]
@ekkekuru2 
各公演の日付について，掲載写真のように表示したいのです．つきましては，以下のお願いと質問があります．
- 現在規定値が「例）1日目第一公演」となっているeventnameを，「第1公演」のように算用数字にした上で「○日目」を削除することは出来ますか？
- 各団体の代表が公演情報（各公演の開始時間や公演名）を編集しますか？それとも，IT委員側の担当者が一括で編集しますか？

<img width="430" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/41de9ad2-8215-4519-b79d-54364464860c">

**Comment by ekkekuru2** [comment]
- 1つ目に関しては↓を参考にv-modelを変更すると変えられると思います
- https://github.com/hibiya-itchief/quaint-app/pull/209

- 2つ目に関しては、現状Eventの操作ができるのはadmin権限なってるので、ITの担当者がやることになると思います。owner権限を持った人が出来るようにすることも出来ますが。

**Comment by ekkekuru2** [comment]
このissue(残席数のアイコン表示)とは少しズレるかもですが、
- 今公園の表示順ってどうなってますか？何かソートされてますか
- 各団体ページの公演を選ぶ部分にEvent.readpermission.nameを表示させたい。例:「2023年度保護者」がこの公演の整理券を取得できます
- Event.readpermissionを元に、ユーザーが取れない公演はもっと目立たないようにしたい。生徒用アカウントでログインした際には保護者の公演は小さく

**Comment by ItsukiKigoshi** [comment]
> 2つ目に関しては、現状Eventの操作ができるのはadmin権限なってるので、ITの担当者がやることになると思います。

- 了解です．IT担当者がやるのなら，規定値「例）1日目第一公演」はそのままで良さそうです．

> 各団体ページの公演を選ぶ部分にEvent.readpermission.nameを表示させたい。

- ユーザにPermissionがない整理券を表示させる必要は無いかも？

> ユーザーが取れない公演はもっと目立たないようにしたい

- 条件付きレンダリングをタグ内で行う（e.g.条件によって<a href="duckduckgo">とか<a href="nothing">とかを切り替える）実装の方法が分かりません．私も同じこと思ってたんだけど，どうすればええやろか

**Comment by ItsukiKigoshi** [comment]
@ekkekuru2 
ここまでのところで特に問題がなければ，PRつくります！

**Comment by ekkekuru2** [comment]
お願いします！
