### ISSUE TITLE
/groupsのページのソート機能

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#234]
とりあえず忘れないようにissueをたてる
フロントエンドのみで実現予定

**Comment by ItsukiKigoshi** [comment]
ここにコメントアウトがありました．
https://github.com/hibiya-itchief/quaint-app/blob/1514e4ac8d6b048827a1345d110d54399e7c3423/pages/groups/index.vue#L126-127

**Comment by hibiyahibiyahibiya** [comment]
ソートに加えて、いま変になっている団体を表示する順番も整理する

**Comment by hibiyahibiyahibiya** [comment]
YouTubeより抜粋
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/57818fb9-7cb5-4f53-91cc-337808f9aa33)
このように、タグ機能・ソート機能をdialogで両立する案はどうでしょうか！！！このissueの範囲外に及ぶ結構大きな変更にはなりますが、かなり簡潔にまとめられます！！！

**Comment by hibiyahibiyahibiya** [comment]
![Screenshot_20230814-111842~2.png](https://github.com/hibiya-itchief/quaint-app/assets/128669695/d272a343-c7ee-4d61-ad8c-bc55d5969655)
スマホ表示
