### ISSUE TITLE
/groups スマホで「お気に入り」が表示されない

### ISSUE THREAD

**Issue by ItsukiKigoshi** [hibiya-itchief/quaint-app#236]
横幅が狭いデバイスではv-chips内に「お気に入り」が表示されなくなります．しかし，[ 【案】Bottom Navigationの整理 #233 ](https://github.com/hibiya-itchief/quaint-app/issues/233) で指摘した通り，「お気に入り」がここにある必然性は無いかと思うので，このbug fixは優先度低めです．
![image](https://github.com/hibiya-itchief/quaint-app/assets/67095865/8e0caad8-739b-4c42-a7f2-b5347944f727)

**Comment by hibiyahibiyahibiya** [comment]
いまは1~3年生のタグ3つしかないですが、
今後は増える(去年何があったか忘れちゃいました)と思うので、結局このバグと対峙することになる気がします
お気に入りタグと他とを分ける縦棒が原因だったら別に大丈夫なんですが

**Comment by ItsukiKigoshi** [comment]
個人的には縦棒が怪しい気がします．
