### ISSUE TITLE
リロード後にボタンが動作しなくなるバグ

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-app#239]
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/2f3ffc4b-574e-4fce-b808-57265a1573d1)

ブラウザで再読み込みをかけたり、リンクから直接飛んだりすると、このように本来青いはずの「映像で鑑賞」ボタンが黒くなり、画面内の一切のボタンが反応しなくなります。
左上の3本線のハンバーガーメニューや、画面下のbottom navigationは押せるので、layout/default.vue内のボタンは動作しているのかなという推測

### 発生した環境
- iPhone SE (2020) iOS 16.5.1
- Safari

- 普段開発に使っているWindowsパソコンでは見たことがない
- また、僕は普段iPhoneではSafariしか使わないので他のブラウザで検証してみる？

同様の状況に遭遇した人がいたら教えてもらいたいのと、もし時間があれば検証してもらえるとすごい助かります、！！！

**Comment by hibiyahibiyahibiya** [comment]
SurfaceのFirefoxで遭遇しました
リロードせずに遭遇した記憶があります

「この団体を編集」ボタン押したら一回エラーが出て、リロードしたら正しいページになりました（これはeditページのバグで関係ないかもしれません）

他のボタンは試していません
