### ISSUE TITLE
fix: 「戻る」ボタンの位置を変更したい in /groups/_groupId

### ISSUE THREAD

**Issue by ItsukiKigoshi** [hibiya-itchief/quaint-app#240]
現在，左端に表示されている戻るボタン（＜）を中央のv-card上部に移したいです．意見を聞かせてください．現状の仕様になっている理由が特にあれば，変更しません．
<img width="1680" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/93cce449-47ba-4307-a1d2-95c8f271f813">

**Comment by ekkekuru2** [comment]
あ、同じこと思ってました
僕は移して良いと思うので、ぜひやっていただけるとありがたいです！
