### ISSUE TITLE
/groups/_groupId エラーメッセージを作成 when 同時刻の整理券取得，配布終了（赤色）の整理券取得，入校処理していない人による整理券取得時

### ISSUE THREAD

**Issue by ItsukiKigoshi** [hibiya-itchief/quaint-app#244]
現状，以下の操作をすると「予期せぬエラー」と出る．予期しよう．
- 既に取得している整理券と同時刻の整理券を取得しようとした時
- 完売（赤色・❌）している整理券を取得しようとした時
- 入校処理していない人が整理券を取得しようとした時
- すでにその整理券を所持している

**Comment by ekkekuru2** [comment]
Duplicate of #197

**Comment by ekkekuru2** [comment]
API側ではそれぞれの場合に対応したエラーメッセージを返しているので、フロントエンドでそれをcatchして欲しい

#197 では @hibiyahibiyahibiya がアサインされてたけどそのまま @hibiyahibiyahibiya にお願いしていいですか？

**Comment by ekkekuru2** [comment]
https://api.seiryofes.com/docs#/tickets/create_ticket_groups__group_id__events__event_id__tickets_post

ここでAPIが予期しているエラーレスポンスもドキュメント化されてます

**Comment by ekkekuru2** [comment]
いや待って一応ちゃんとAPIからのエラーメッセージをcatchして表示するコードはあるな↓

https://github.com/hibiya-itchief/quaint-app/blob/1514e4ac8d6b048827a1345d110d54399e7c3423/pages/groups/_groupId/index.vue#L558-L560

し、以前はこれがちゃんと機能してた記憶がある。いつまで動いてたかは覚えてないけど、、、

このコードの意図は
- e.responseがundefinedでは無い(=予期せぬエラーでは無く、APIが正しくエラーを処理して返ってきたエラー)である場合に
- e.response.data.detail (APIからのエラーの詳細)をthis.error_messageにそのまま代入する

だと思うんだけどなんで機能していないんだろう

**Comment by hibiyahibiyahibiya** [comment]
if(e.response)じゃなくてif(e.response!==undefined)にすればいいんじゃないでしょうか？
if()の中身が式じゃないときの仕組みがよくわからないのですが、これってtrueかfalseかを判定しているんじゃないんですか？つまり、undefinedかどうかを判定してるわけではないのではないでしょうか
