### ISSUE TITLE
一般向け整理券の残席状況もサイト上で確認できるようにする

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-app#250]
今年一般客はサブアリでの紙整理券の配布となった。整理券自体は紙だが、その残席状況をオンラインで確認できるようにしたい

**Comment by hibiyahibiyahibiya** [comment]
残席状況を載せる階別校内地図のページを作る案もありましたよね。
高校内に同ページ画面をプロジェクター等で用意するという案はどうしますか？
その場合生徒、保護者、一般、どの残席状況を表示するかという問題もありますが…

**Comment by ekkekuru2** [comment]
これはあくまで現行の/groups/_groupIdページ内の話ということにして、
それら２つはまた別のissueにしよう
立ててもらっても良い？

**Comment by hibiyahibiyahibiya** [comment]
target: paperの整理券は未ログイン時表示されるようになっているので、closeします
