### ISSUE TITLE
PR #247(/_groupIdの調整)の議論

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#256]
### 再読み込みの左のアイコン

![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/029f9941-f7fc-4409-a822-8bf46da406a2)
これが現行の表示。
この `mdi-reload` が個人的には小さい方が好ましいと思い、友達に聞いてみたところ(n=2)
1人は大きい、つまり今のまま、もう1人は小さい(`class="small"`)ほうがよいと答えた。
iconとtextの間にちょっとスペースを入れるなどすれば違和感が取り除かれるかもしれない

### 残席表示の基準について
今後、

* 一般の方の
* 保護者の
* 生徒の
と「残席」という言葉が3種類の意味を持つと考えると、それを切り替えるボタンが必要？
今の表示だとどの残席状況なのかがわからない。
切り替えるボタン(イメージは右上に用意)については要検討

### 残席表示の文字の表現について

△時、「僅少」となっているが
単純に「僅か」「わずか」「残り僅か」「残りわずか」
のどれかでいいと思う

### 残席表示の文字色について
緑色は比較的見やすいが、他の色が見づらい
下は「完売」をboldにしてみたもの
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/b0f6bb58-3a0b-4902-94a9-2c1828cc9fe0)

**Comment by ItsukiKigoshi** [comment]
> 残席表示の基準について

→ログインしているアカウントの属性（生徒・保護者・生徒）をフロントエンドで把握できるなら，その属性に合った整理券（生徒がログインしてる時は生徒用整理券）だけ表示するのでいけませんかね？

> 残席表示の文字色について

→それは私も感じました．取得できない整理券のv-cardがdisabledになっているので，見にくくなっていると思います．bold良い感じですね．

-  「再読み込みの左のアイコン」「残席表示の文字の表現」については．現状私の好みで実装しているので，ぜひ改善していただきたいです．

**Comment by hibiyahibiyahibiya** [comment]
> ログインしているアカウントの属性（生徒・保護者・生徒）をフロントエンドで把握できるなら，その属性に合った整理券（生徒がログインしてる時は生徒用整理券）だけ表示するのでいけませんかね？

それでよいと最初は思ったのですが、利用者間で画面が違うのは混乱するかな、と
(例えば生徒が親に使い方を説明するため一緒に見ていたら、残席状況の表示が違うことに気づき質問する、という流れができてしまうかなと)
そのため今どの種類の残席状況を表示しているのかを明示しておきたいと思いました

**Comment by ItsukiKigoshi** [comment]
なるほど！
それでは，画面上部に「あなた（保護者）が取得できる整理券が表示されています．」の一文を出すのはいかがでしょう．
「切り替えるボタン」はスタッフ生徒を除く殆どの人にとって不要な機能なので，無くて良い気がしました．

**Comment by ekkekuru2** [comment]
> ログインしているアカウントの属性（生徒・保護者・生徒）をフロントエンドで把握できるなら，その属性に合った整理券（生徒がログインしてる時は生徒用整理券）だけ表示する

> 「あなたが取得できる整理券が表示されています」

- #250

紙整理券の情報を入れる場合、どうしましょう

**Comment by ItsukiKigoshi** [comment]
紙整理券の情報をseiryofes.com内に入れるとごちゃごちゃしない？
紙整理券の情報は，映画館のように，体育館のスクリーンにのみ表示されるとかして，紙とデジタルを棲み分けした方が良い気がしました

**Comment by ekkekuru2** [comment]
あーたしかにごちゃごちゃしますね
今年、3年の紙整理券はサブアリ、1,2年の紙整理券は剣道場で配布らしくて、結構そこまで行くだけで大変なのかなと思われるのでWebページで確認できるようにするメリットがあるかなーと思ってたんですけど。

**Comment by ItsukiKigoshi** [comment]
体育棟前のアーケードとか校内にディスプレイを置いて空き状況を表示するとか？
ってか紙の整理券の空き状況って現状収集してないよね．紙整理券の配布担当者が空き状況を手入力するの？

**Comment by hibiyahibiyahibiya** [comment]
紙の整理券を配布する人が、たとえば配布率80%になったらこのボタンを押してね、という形式の予定です

**Comment by ItsukiKigoshi** [comment]
紙整理券への対応をどうするかは，どんな実装にするか候補をいくつか挙げた上でDiscord会議とかを用いてdiscussionできたら良きかも？会議開くのどうでしょう．

**Comment by ItsukiKigoshi** [comment]
新幹線の案内表示がよくまとまっていた．
![Uploading 3320A01B-0
![2481C17F-EEA1-4CCE-9254-46D7840AE9CB_1_102_o](https://github.com/hibiya-itchief/quaint-app/assets/67095865/de5746eb-af86-44d9-9ed6-07e09bb0d25e)
AD9-4AC5-9A1F-5C3455835390_1_102_o.jpeg…]()

**Comment by hibiyahibiyahibiya** [comment]
構内に設置する画面に、
その日の第1〜5公演を
〇〇✕〇△
みたいに表示するという案を思いつきました
（また、1日目と2日目を切り替えるボタンも用意すれば当日前に確認できる）
結構便利だと思います
