### ISSUE TITLE
<template>の誤字を撲滅する

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#257]
以前、
`v-container`が正しいところを、`v-conteiner`と誤字っていたところ、どこでもエラーが出ていなかった。
これはcontainerだなと勝手に判断してくれたのか、それとも無視されたのか…

また、`class`が`clsss`と誤字っていたのも発見したことがある。

全部目視で確認する必要があるかもしれない？

**Comment by ItsukiKigoshi** [comment]
これを使っても認識しませんか？
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
