### ISSUE TITLE
トップページに最低限の内容を入れる

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-app#258]
- 他校に送るポスターをとりあえずのメインビジュアルに据える(できれば文字アニメーションしたい)
- [学校ホームページ](https://hibiya-h.metro.ed.jp/onesheet5.html) に載っているような最低限の案内(日時,時間,一般も入れること)などを載せる
- カウントダウンをとりあえずつくる
- チーフ会Twitter?

**Comment by ekkekuru2** [comment]
- メインビジュアル

https://github.com/hibiya-itchief/quaint-app/blob/254-ogp%E5%AF%BE%E5%BF%9C/static/ogpimage.png

![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/1243f386-1a27-4082-a3e1-3e63ee6fa2f4)

このあたりの画像を駆使して、パソコン・タブレットサイズの場合は1画面分、スマホサイズなら半画面分くらいのサイズのメインビジュアルを作る

出来ればふわっとアニメーションしたい

**Comment by ekkekuru2** [comment]
@ItsukiKigoshi 
カウントダウンは今ちょっとだけ作ったので(まだプッシュはしてない)、メインビジュアルか、基礎情報をお願いしても良いですか？

**Comment by ItsukiKigoshi** [comment]
@ekkekuru2 
> カウントダウンは今ちょっとだけ作ったので(まだプッシュはしてない)

プッシュお願いします！

**Comment by ekkekuru2** [comment]
しました！
