### ISSUE TITLE
ハンバーガーメニューとボタンの表示重複

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#261]
ハンバーガーメニューと下の諸ボタンの表示が被ることがある

おそらくいま幕が透明だから起きていると予想します

また、ハンバーガーメニュー含む上の幕にログイン中かどうかを表示すると親切なのではないかと。

委員長からの寄稿

**Comment by ekkekuru2** [comment]
そう、初見の人にはログインがどこか分かりづらいよね

**Comment by hibiyahibiyahibiya** [comment]
でもデザイン的にはない方がきれい
ハンバーガーに翳したときに灰色の丸みたいなのを表示するのが折衷案と思われる
