### ISSUE TITLE
/groupsの絞り込みタグをページ変遷後も維持

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#262]
いまはページを開くと必ず「すべて」の表示になる
なので
「2年」タグを選択→団体見る→戻るボタン押してもどる→「すべて」タグが選択されている
と少し使いづらい
特に2年の団体を21から28まで一つずつ見ていくときなどに、毎回選択するのは面倒

* タグ選択するごとにURLを変える
* 一時的なキャッシュにどのタグを選択していたか記録する

タグに加えて検索ボックス内の内容も引き継げたほうがよさそう？

委員長からの寄稿

**Comment by ekkekuru2** [comment]
あー確かに！
Googleみたいにクエリパラメータつけるか
/groups?q=検索語句&tag=洗濯中のタグ
みたいな感じです

**Comment by hibiyahibiyahibiya** [comment]
その場合、選択タグを変えるたびに履歴に記録されたりしませんかね？
Twitterとか使ったあとに履歴見ると何十個もTwitterが並んで非常に面倒なんですが、あれを作り出してしまうのかなと。

**Comment by ekkekuru2** [comment]
あー確かに嫌だねそれはその視点は無かった

確かNuxt、アドレスバーに書かれているパスを、表示だけ変える(実際に遷移はしない。から履歴にも残らない)っていうことができたはず
nuxt path 書き換え とかでググってみて
