### ISSUE TITLE
/ticketsの表示が左上

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#266]
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/c48a46c6-f8b7-499c-a695-cbea39352974)
PCでの表示
たぶんすぐ直せると思います

**Comment by hibiyahibiyahibiya** [comment]
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/9b08af6a-70ef-4d68-8d5c-f88290f39d64)
まだ整理券がない時は「あなたの整理券」欄にまだありませんみたいなことを記しておいた方がよいのではないかと

**Comment by ItsukiKigoshi** [comment]
このv-cardを<v-col cols=“12”>タグ内に入れれば解決すると思います．ただ，殆どの人がスマホで整理券を取得すると考えれば，このfixの優先度は低いかも？
![image](https://github.com/hibiya-itchief/quaint-app/assets/67095865/04a64c2a-74e2-4402-80fc-1e7525de8639)

**Comment by hibiyahibiyahibiya** [comment]
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/6526b2a5-5fa1-45c1-9ff8-3fb3ab2883e4)
ちゃんと`v-btn`は`block`になっているのになぜなんだろう

**Comment by hibiyahibiyahibiya** [comment]
調査の結果、単純に文字数が多いからblock以上の長さになってしまうのだと合点しました
600pxからこのバグが起きるので、600px時点で正常に動作するのは14文字まででした
(現在は「次に見たい公演を探しに行きましょう✨」と18文字)

また、表示が左上にある点については、右に「あなたの整理券」があることを踏まえれば別にそのままで良い動作な気がしたので、本来のissue内容は解決とします
