### ISSUE TITLE
/groupIdの公演表示の、選択されるcardについて(些細)

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#267]
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/ab1f6291-acf0-41a1-8a4c-d97298db39c4)
このように、残席状況にカーソルを合わせてクリックすると、dialogは出るものの、残席状況ボタンだけ反応してるように見えてちょっと違和感を与えてしまうかも

直す手段がなければ諦めます

**Comment by ItsukiKigoshi** [comment]
v-btnをdisabledにするとこの問題は解決するんですが，見にくくなってしまうんですよね．操作に問題は無いかと思うのでcloseさせていただきました．
