### ISSUE TITLE
一般客の整理券取得に関する案内

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-app#271]
今年一般客は紙なので、整理券タブのログインダイアログの下に配布場所や時間帯などの案内を載せる
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/b2747199-094d-4223-b536-fb01e7a99ae7)

**Comment by ItsukiKigoshi** [comment]
一般客向けの案内，トップページに載せるのはどうでしょう．ログイン画面に案内があるのは分かりづらい気がします．

**Comment by ekkekuru2** [comment]
現状の動作だと、未ログイン状態で/ticketsにアクセスすると /login 画面に飛ばされますが、そうではなくて、未ログイン状態で下のv-bottom-navigationの「整理券」ボタンを押して/ticketsにアクセスすると、ログインフォームと一般客向けの案内が同時に出るってかんじのイメージです

今年は一般客のログインが無いため「一般の方はこちらから」ボタンを削るので、ログインフォームの高さはもっと低くなる(すぐに一般客向けの案内が見える)し、「整理券」タブに「整理券の案内」がある方が分かりやすいかなと思ったんですが

**Comment by ItsukiKigoshi** [comment]
了解しました！そのままの挙動で大丈夫です．ただ，一般客にどうやって「整理券」ボタンを押してもらうかを考えないとですね．

**Comment by ekkekuru2** [comment]
んーたしかに

トップページに「今年の整理券についてはこちら」みたいなバナーを作ってリンクするとか、、？

**Comment by hibiyahibiyahibiya** [comment]
* #437
