### ISSUE TITLE
【議論】最初にアイコンを表示するか否か

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#276]
![Screenshot_20230808-185546.png](https://github.com/hibiya-itchief/quaint-app/assets/128669695/56dfb57e-a8d0-4b99-8faa-3f75be88348c)

![Screenshot_20230808-185554.png](https://github.com/hibiya-itchief/quaint-app/assets/128669695/089f1bd0-755f-4b47-a61d-5cb0f954edfc)

このようにアプリを立ち上げたときにアイコンを表示するかどうか

入れると少しサイトを開くのに時間を要してしまうのが悩み

**Comment by ekkekuru2** [comment]
かっこいい😎
けどあまり必要性はなさそう…
PWAの時だけ出るとか？

**Comment by hibiyahibiyahibiya** [comment]
それ思いました
ただ、(自分のスマホだけかもしれませんが)PWAだと起動の際に5秒ほど白画面があって結構ストレスなので、さらに遅延するのはよくないのかな…と

**Comment by ekkekuru2** [comment]
あーそんなにスペックによって差があるのは知らなかった
白画面は良くないね
それを考えると入れていいかも

**Comment by hibiyahibiyahibiya** [comment]
https://github.com/hibiya-itchief/quaint-app/assets/128669695/f20bc5f9-7b73-4e23-bd6d-1d0de65f62f6

このような演出を入れる案あり。

**Comment by hibiyahibiyahibiya** [comment]
結局
* #407 

で実装
