### ISSUE TITLE
アクセス案内

### ISSUE THREAD

**Issue by ryu-kjtn** [hibiya-itchief/quaint-app#280]
保護者や一般の方も来校されるので、学校へのアクセス案内もサイト内にあると便利だなと思いました

【参考】
2018年の星陵祭ホームページ内のアクセス案内
[https://hibiyahighschool2018.wixsite.com/seiryofes-2018/blank-3]

<img width="834" alt="2023-08-09 (1)" src="https://github.com/hibiya-itchief/quaint-app/assets/141553878/f921ba07-4331-45ee-8385-95dee2c90a7d">
<img width="940" alt="2023-08-09" src="https://github.com/hibiya-itchief/quaint-app/assets/141553878/7a262fde-395d-4633-a283-0eea62256de5">

**Comment by ryu-kjtn** [comment]
名乗るの忘れてました
IT委員会の委員長の梶谷です

**Comment by hibiyahibiyahibiya** [comment]
https://github.com/hibiya-itchief/quaint-app/pull/278
これで解決
一足遅かったな

だけど駅とその出口についての記述はあると親切かもね

**Comment by ItsukiKigoshi** [comment]
PRを作成したモノとして，https://github.com/hibiya-itchief/quaint-app/pull/278のアクセス案内は不親切なのでもう少し親切にしたいです．とりあえずhttps://github.com/hibiya-itchief/quaint-app/pull/278で，何もアクセス情報が掲載されていない現状に対する応急処置はしました．

**Comment by ryu-kjtn** [comment]
よろしくお願いします。
ありがとうございます

**Comment by ekkekuru2** [comment]
Google Mapは必須よね
駅からの歩き方書いてあると丁寧で良い

**Comment by ryu-kjtn** [comment]
今年も星陵祭当日は正門が使えなくなるそうです。
サイトのスペース的に道順等のアクセス案内が入らなかったとしても、正門が使えないということは必ず書いておきたいです。

**Comment by hibiyahibiyahibiya** [comment]
これって
2023.seiryofes.com/access
みたいに、別ページに分けますか？

**Comment by ekkekuru2** [comment]
俺はトップページの下の方がいいと思う

**Comment by hibiyahibiyahibiya** [comment]
https://hby2019.wixsite.com/website/hbyseiryoaccess
やdiscordの文章が参考になる
