### ISSUE TITLE
【議論】/groups クラス劇と、Hebe含む有志団体の違いを踏まえた表示

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#283]
* クラス劇は整理券の取得も行うが、有志団体は時間帯の提示のみ。
* またクラス劇は何公演もあるが有志には1度しか行わないものがある。

などを踏まえ、同じ/groups内で表示するのかの議論。
github内issueで議論するのが相応しくなければcloseしても大丈夫だと思われる。

(/groups…「探す」ページのこと)

**Comment by hibiyahibiyahibiya** [comment]
個人的に、展示についてもサイト上に載せたい
(社会科ホールに展示してある作品などのイメージ)

**Comment by hibiyahibiyahibiya** [comment]
これvuetifyドキュメントからの抜粋なんですが
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/b0747299-6f62-4fe9-a922-2701d286a30d)
こんな感じで上にクラス劇、下に有志団体とするのはどうでしょう
両subheaders(画像で言う Places to Beの文字のこと)へのリンクをページ上部に用意すれば使いやすいと思います

**Comment by ItsukiKigoshi** [comment]
良いと思います！もしくは，[五月祭のサイト](https://gogatsusai.jp/96/visitor/search/)みたいに
1. 発表方法
2. ジャンル
をv-chipsで二段に分けて表示することで，実装が簡単かつシンプルで見やすいかも知れません．いかがでしょう？
<img width="1079" alt="image" src="https://github.com/hibiya-itchief/quaint-app/assets/67095865/3ef4bf6e-3d56-4262-ba8d-54b01e57346c">

**Comment by ekkekuru2** [comment]
クラス劇か有志かはどう判別しますか？
現状APIからそのデータはレスポンスされてないわけだけど
僕がぱっとおもいついたのは3つ
1. API側でその情報を持つ
  単純だし普遍的だけど、ちょっとめんどい
2. 特定のタグを結びつけて管理
  既存のAPIで出来るけど、タグの名前に見えない制約(フロントエンド側であらかじめ予約されている名前は使えない)が付くのが嫌かも
3. group_idを正規表現で判別？
  group_idが「数字2桁+r」ならクラス劇、みたいな？でもこれも結局フロントエンド側の予約語になってることは変わらないか

**Comment by ItsukiKigoshi** [comment]
クラス劇/有志/hebe を，この写真で言うところの「発表方法」で識別するのでどうかな．つまり2案．

![](https://user-images.githubusercontent.com/67095865/260302145-3ef4bf6e-3d56-4262-ba8d-54b01e57346c.png)

**Comment by hibiyahibiyahibiya** [comment]
Hebeについて周知ができればそれでいいと思います(2の案)

**Comment by ekkekuru2** [comment]
あーなるほど、それが良さそう

**Comment by hibiyahibiyahibiya** [comment]
* https://github.com/hibiya-itchief/quaint-app/issues/234#issuecomment-1676578148

この形式でソート機能とタグ機能合併するのはいかがでしょう
今まだUI考えていますが、ごちゃごちゃしないためにもこちらの方が良いと思います

**Comment by hibiyahibiyahibiya** [comment]
昨年のHebeについてあまり覚えていないのですが、他の有志団体と性質が大きく異なるのであれば「Hebe」という別枠として用意しますか？

**Comment by ekkekuru2** [comment]
その方が良さそう

**Comment by hibiyahibiyahibiya** [comment]
いま、タグを完全にこちらで指定するやり方で作っていますが大丈夫でしょうか。
つまり、1年、2年、3年のようなタグをAPI関係なくフロント側で用意する感じです

**Comment by ItsukiKigoshi** [comment]
> いま、タグを完全にこちらで指定するやり方で作っていますが大丈夫でしょうか。 つまり、1年、2年、3年のようなタグをAPI関係なくフロント側で用意する感じです

「こちら」はIT委員会のことでしょうか？もう少し詳しく教えていただきたいです．

**Comment by ItsukiKigoshi** [comment]
@hibiyahibiyahibiya 
以下のIssueも一緒にresolveしていただけますか？
- https://github.com/hibiya-itchief/quaint-app/issues/236

**Comment by hibiyahibiyahibiya** [comment]
言葉足らずすみません！フロントエンドのことです
具体的には #307 のbranchで実装するつもりの内容です
