### ISSUE TITLE
配色

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-app#287]
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/26f83466-6d7e-4fff-a445-4c3388f6625b)
これはチーフ会内のものらしいがこんな感じで使う色パレットを決めておきたい

**Comment by hibiyahibiyahibiya** [comment]
メモ：「祭徠」の色は#b49656
primaryなどと同様に"sairai"と指定すれば出る
