### ISSUE TITLE
/groupsをリロードした際のxs仕様→sm仕様→md仕様

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#292]
/groupsをリロードした際に遭遇する。

![スクリーンショット (73)](https://github.com/hibiya-itchief/quaint-app/assets/128669695/a048c487-d99a-4ea5-b110-96503d4167aa)
![スクリーンショット (72)](https://github.com/hibiya-itchief/quaint-app/assets/128669695/f8daa3c6-5247-412c-bf8f-52e7e6e32d64)
![スクリーンショット (71)](https://github.com/hibiya-itchief/quaint-app/assets/128669695/4982ba8f-f655-4e91-94f6-be7c9c7856c4)

この3仕様が一瞬表示される。
仕様であって直す術がないならcloseする。

**Comment by ItsukiKigoshi** [comment]
殆どの人は当日スマートフォンで閲覧すると考えると，気にしなくていいかと思います．私は無視していました．

**Comment by hibiyahibiyahibiya** [comment]
一応、 
* #386 

がマージされれば、nowloading中は表示されないのでばれない
ただし、callbackページはたぶんもろにアウト
