### ISSUE TITLE
APIの仕様変更に基づく変更依頼

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-app#300]
当初は1つ1つissue作ろうと思ったんですけど、それより、APIのどこが破壊的変更になっているのか一覧できた方が分かりやすいと思ってこのような形にしました
## 公演の座席枠を分けられるようにした
8月10日の会議でフロントエンドは @ItsukiKigoshi の分担となったのでアサインしました。
- #296
に関連して
- https://github.com/hibiya-itchief/quaint-api/pull/126
をしました。
Discordの鍵付きの#技術部にそれぞれのRoleが付いたアカウント情報を載せたので、APIが期待通りの動作をするかのテスト(一応一通り確認しましたが不安なので)もして欲しいです。

## 整理券を論理削除にしました
- https://github.com/hibiya-itchief/quaint-api/pull/119
削除された整理券や、その他使用できない整理券もレスポンスに含まれるようにしたのでフロントエンドでフィルターをお願いします

## 一般向けの紙整理券の残席状況表示への対応
やるかどうかは別としてできるような仕様にした
というのも、1つ目のUserRoleと、ticket.statusを活用して実現している
- #250
やるのであればこのissueも関連する

**Comment by ItsukiKigoshi** [comment]
- [ ] 公演の座席枠を分けられるようにした
- [ ] 整理券を論理削除にしました
- [ ] 一般向けの紙整理券の残席状況表示への対応→対応予定無し

**Comment by ItsukiKigoshi** [comment]
Notes: フロントエンドでtickets=[]に直接filterをかけて，各ユーザ属性に合ったticketsのみフロントに呼び出す．
