### ISSUE TITLE
星陵祭終了後の表示

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#310]
メインページが変わる？
どのタイミングで切り替わる？
自動でなされるようにする？それとも手動でデプロイする？

とりあえずissueだけ立てておくめも

**Comment by ekkekuru2** [comment]
しばらくは残しておきたいよねー(たぶんこういうことじゃないよね)

**Comment by hibiyahibiyahibiya** [comment]
そのあたりも含めて
