### ISSUE TITLE
存在しないページに飛んだ時の表示

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#311]
/groups/hogehoge
の場合は中身がない`/_groupId`のページが表示される
(おそらく v-if="group"だかが理由で表示されない)
![スクリーンショット (79)](https://github.com/hibiya-itchief/quaint-app/assets/128669695/399a69f5-80d1-4452-a5ec-1032e3166122)
おそらくそれ以外の場合はすべて、画像などを読み込めていない白地のトップページが表示される
![スクリーンショット (80)](https://github.com/hibiya-itchief/quaint-app/assets/128669695/2159688e-c2a0-40d2-9064-87569ba74475)
![スクリーンショット (81)](https://github.com/hibiya-itchief/quaint-app/assets/128669695/cd7ace99-25ca-4ee1-b396-1a5c045ff339)

https://github.com/hibiya-itchief/quaint-app/blob/develop/layouts/error.vue
の404ページが機能していないから？

#244 もそうだが、全体的にエラー関連がうまく動作していないように思われる

**Comment by ekkekuru2** [comment]
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/f9f8535a-c58f-4a57-94b0-9a810bca8aaf)
これかも client side default fallback
