### ISSUE TITLE
各公演のtargetをフロントエンドで指定できるようにする in /groups/_groupId/edit

### ISSUE THREAD

**Issue by ItsukiKigoshi** [hibiya-itchief/quaint-app#316]
現状は以下の通り．
![Screenshot 2023-08-20 at 23 41 29](https://github.com/hibiya-itchief/quaint-app/assets/67095865/ccd9ad3d-2aea-4649-a02b-436b07d7aed3)

しかし，
- https://github.com/hibiya-itchief/quaint-api/issues/118#issue-1839553838
に書かれているtargetが以下のように
- admin
- owner
- entry
- everyone - インターネット上の誰でも
- paper - 紙整理券による配布(通常の方法では取得することができない)
- b2c - B2Cアカウントを作成した人ならだれでも
- b2c_visited - 入校処理をした(jobTitle="2023Visited")B2Cアカウント
- ad - Azure ADのアカウント
- parents - 保護者の事前配布アカウントを所属させたAzure ADのグループ
- student - 生徒
- school - 生徒と先生の学校から配布されたMicrosoftアカウントを所属させたAzure ADのグループ
- visited - b2c_visitedとadの和集合
- visited_parents - b2c_visitedとparentsの和集合
- visited_school - b2c_visitedとschoolの和集合
- school_parents - schoolとparentsの和集合
と大量に追加されているので，フロントエンドから，必要なものは全て指定できるようにしたい．

**Comment by ItsukiKigoshi** [comment]
ついでに，公演名のデフォルトを
「第1公演【保護者】 」（「第○公演【（対象）】」）
の形にしてほしいです．

**Comment by ekkekuru2** [comment]
いいと思います

**Comment by ItsukiKigoshi** [comment]
[こちら](https://github.com/hibiya-itchief/quaint-app/issues/316#issuecomment-1687259890)のコメント，editいたしました．改めて，公演名は
「第1公演 」
（日付を入れない）にしてほしいです．

**Comment by hibiyahibiyahibiya** [comment]
とりあえず今年は
- student - 生徒のみ
- parents - 保護者のみ
- school - 生徒・先生
- school_parents - 生徒・保護者・先生

を実装しようと思います
来年以降は #389 で
