### ISSUE TITLE
サムネ画像が表示されていない

### ISSUE THREAD

**Issue by ryu-kjtn** [hibiya-itchief/quaint-app#333]
12Rのサムネ画像が消えている
これはバグなのか編集者のミスで画像無しのままアップロードしたのか分からないので一応issue立てておきました
<img width="960" alt="2023-08-26" src="https://github.com/hibiya-itchief/quaint-app/assets/141553878/bb9abab9-9957-4435-930a-09e72a7ceb68">
<img width="960" alt="2023-08-26 (1)" src="https://github.com/hibiya-itchief/quaint-app/assets/141553878/76948827-1dc8-4c2f-b217-688706b2c73b">

**Comment by hibiyahibiyahibiya** [comment]
![Screenshot_20230826-122447~2.png](https://github.com/hibiya-itchief/quaint-app/assets/128669695/a65b89fe-ac52-49f0-b97a-e54ac9146021)

このように12Rの編集ページでは画像がアップされてます

**Comment by hibiyahibiyahibiya** [comment]
今見たら12R更新されていました
他の団体も画像が更新されているっぽい

closeしてもいいし、こういう状況が生まれることを書き残す意味でそのままにしててもいいと思う

**Comment by ekkekuru2** [comment]
これ俺も気づいて14:00ごろにとりあえず↓やったら治った。なんで起こったんだろう
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/08024430-417c-4f88-95be-6d3adf2e2fa5)

**Comment by ryu-kjtn** [comment]
今見たら28Rでこの現象起きてました。

ログアウトすると正しく表示されるようになった。
その後ログインし直すとそのまま正しい表示になっていて、バグは治っていた。
ログアウトするという動作がサムネ表示される(バグ解消)きっかけになっている、、、？？

一時的なものならサイトとしては大丈夫だと思いますが、技術的にはどうでしょう、、？
このissueは立てたままの方がいいですか？
