### ISSUE TITLE
画像の上下が切れている

### ISSUE THREAD

**Issue by ryu-kjtn** [hibiya-itchief/quaint-app#342]
PCでクラスのページに飛んだ時、縦に長い画像の上下が切れている。
優先度は低いので、もし余裕があれば調整してもらいたいです。
スマホだと切れずに表示されていました。
　
<img width="960" alt="2023-08-28 (2)" src="https://github.com/hibiya-itchief/quaint-app/assets/141553878/fb360428-5e15-4566-91e5-9e3b74b76291">

**Comment by hibiyahibiyahibiya** [comment]
原因はおそらくこれ
https://github.com/hibiya-itchief/quaint-app/blob/6e8b72ce2ccdaa1817c872002640fa8b574f5f12/pages/groups/_groupId/index.vue#L14
高さの最大値が500ピクセルに設定されてます

**Comment by ekkekuru2** [comment]
当初は意図した動作だったんだけど、結局周知とかがうまくできてなかったり、縦長サムネを登録するクラスも多くて、不具合だと勘違いされるのが増えてるから、`contain`つけてもいいかも
