### ISSUE TITLE
整理券取得の際の人数選択の文言が分かりづらい?

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-app#346]
同時に入場する人数(ご家族など)
これ意味わかりづらいかも。何かいい案ください
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/ca535a0f-03a0-42e6-85a7-7723762463e3)

**Comment by ryu-kjtn** [comment]
「何名分の座席を取りますか？」と疑問形にしてしまうのどうですかね

**Comment by ekkekuru2** [comment]
良いかも、

**Comment by ryu-kjtn** [comment]
ぜひ案のひとつに入れていただければ
