### ISSUE TITLE
/_groupId Hebe等では「観劇予約」を表示しないように

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#355]
クラス劇はオンライン整理券だが、他はそうではない

とりあえず暫定のぷるりくをつくる

**Comment by hibiyahibiyahibiya** [comment]
そしたら、Hebeのidはナンバーだけですから、単純なforで
各hebeのeventをまとめて入手できるかもですね

**Comment by ryu-kjtn** [comment]
これに関係ある話かどうか分かりませんが、Hebeはきっちりタイムスケジュールを作って進めるのではなく、前の団体が終わってしばらくしたら次始めよ、みたいな感じで進めるらしいです。
(チーフに聞いたら教えてくれました)

**Comment by ekkekuru2** [comment]
わお

**Comment by hibiyahibiyahibiya** [comment]
めも
タイムテーブルへのリンクを設置

**Comment by hibiyahibiyahibiya** [comment]
* #437
