### ISSUE TITLE
トップページのデザインの案

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#377]
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/f41618a8-ce08-4246-827d-379f65a7e91a)
こんな感じでアクセス・スケジュールを置く？
五月祭より抜粋

![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/6727d102-3298-439e-b7ce-5dfc3acea778)
こんな感じで「祭徠」の説明とかチーフ会のなんたらとか？
五月祭より抜粋

**Comment by ryu-kjtn** [comment]
祭徠の説明とかっていうのは特集ページのこと、、？

**Comment by hibiyahibiyahibiya** [comment]
祭徠の由来って特集ページ？
「チーフ会の何たら」が特集ページのつもりでした
