### ISSUE TITLE
0.5.0の修正　/groups Nuxtconfigじゃできない

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#379]
「デフォルト順」を押して並び順が変わったらそれはアウト

**Comment by hibiyahibiyahibiya** [comment]
え、ほんとですか？
/groupsを開いたときの順番と、デフォルト順を押した(=idでSortGroupsを行う)後の順番が異なるんですが…

**Comment by ekkekuru2** [comment]
え一応確認なんだけどnuxt generateしてる？

**Comment by hibiyahibiyahibiya** [comment]
いえ、yarn run devでの動作のみです
nuxtconfigだとnuxt generateのみしか対応できない感じですか…？

**Comment by ekkekuru2** [comment]
というか逆かも
毎回/pages/groups.vueでソートをするのはクライアント側の負荷が多少なりともあるから
nuxt generateするときにソートするためにnuxtconfigを変更した

**Comment by hibiyahibiyahibiya** [comment]
APIをGETするときに必ずnuxt generate(ここでは特にnuxtconfig)を通るってことですか…？

**Comment by ekkekuru2** [comment]
んー違う

**Comment by ekkekuru2** [comment]
https://github.com/hibiya-itchief/quaint-app/blob/6e8b72ce2ccdaa1817c872002640fa8b574f5f12/pages/groups/index.vue#L214-L221

nuxt generateをするときに1回だけAPIを呼んで、それがフロントエンド側に保存されていて、/pages/groupsを開いたときにasyncDataのpayloadに渡される

**Comment by hibiyahibiyahibiya** [comment]
そしたらyarn run dev時に順番がごちゃ混ぜになるのは放置ってことでいいでしょうか？
