### ISSUE TITLE
Component化

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-app#425]
例：/_groupIdの整理券のv-cardと、/_groupId/dataの整理券のv-card

現状、トップページのCountDownがそれ？

**Comment by ekkekuru2** [comment]
- /groupsの各団体のカード
- この見出しもコンポーネントにしてもいいかも(今年限りになりそうだけど)
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/d2384371-9c1a-4c70-9851-4dfedf914c3a)

**Comment by hibiyahibiyahibiya** [comment]
Duplicate of #546
