### ISSUE TITLE
フロントの表示が遅すぎる

### ISSUE THREAD

**Issue by ItsukiKigoshi** [hibiya-itchief/quaint-app#57]

**Comment by Ekke-kuru2** [comment]
サーバーのスペックがボトルネックかなと推察されます。そこの検討をするならAzureを早めに契約した方がいいかもです。

**Comment by Ekke-kuru2** [comment]
axiosでAPIにリクエストを送るときに今までは1個終わったら次やるそれが終わったら次・・・というように直列処理だったのが原因だったみたいです。Promise.allっていうのを使ってリクエストを並列で処理するように書き直しました！

**Comment by Ekke-kuru2** [comment]
TODO:SSRのオンオフも比較する

**Comment by Ekke-kuru2** [comment]
#63
