### ISSUE TITLE
Groupsのデータを直接Dataに載せる in /pages/groups/index.vue

### ISSUE THREAD

**Issue by ItsukiKigoshi** [hibiya-itchief/quaint-app#75]
これにより，
- groupsの情報は変更されても自動反映されなくなる。
- 「いいね機能」は存続（groupの個別ページでは一回ずつバックエンドからデータを持ってくるから）

**Comment by ekkekuru2** [comment]
- #95
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/19884136-ff62-47fb-94b3-2c785c3cd556)

で実現できました！
