### ISSUE TITLE
Loginにリダイレクトされている挙動がどこから来ているのか突き止める

### ISSUE THREAD

**Issue by ItsukiKigoshi** [hibiya-itchief/quaint-app#8]
コード読めない。もしかしてサーバーサイドも起動している状態じゃないとログインできない？今度えいすけに聞く。

**Comment by Ekke-kuru2** [comment]
そうなんです。バックエンドAPIを起動してないとログインは成功しないです

**Comment by Ekke-kuru2** [comment]
@ItsukiKigoshi もしかして実際に動かしてくれてますか？

**Comment by ItsukiKigoshi** [comment]
実際に動かしてます！
バックエンドのお勉強までは手が回らないので，ひとまず自分でNuxtプロジェクトを作ってそっちで色々作ってみてます！！

**Comment by Ekke-kuru2** [comment]
すごくありがたいです開発の孤独感が薄れます笑
